sudo: false

before_install:
  - gem install asciidoctor coderay;
#  && gem install asciidoctor-pdf --pre;

script:
  - echo Building docs;
    cd 2016-05_netCDF-CF_Workshop;
    ./adoc2html.sh 2> build.log;
    if [ -s build.log ]; then
       echo Doc build produced errors:;
       cat build.log;
       false;
    fi;

after_success:
  - ls -ale;
